# Glass - Kitty Terminal Colors
foreground              #C6D9E4
background              #0B1621
selection_foreground    #E7F2F7
selection_background    #1B3549

color0  #132332
color8  #46627A
color1  #E0868A
color9  #EDA3A5
color2  #7CCFB6
color10 #9FE0CC
color3  #E3C58C
color11 #F0D9A8
color4  #6EA6DA
color12 #93BFEA
color5  #B79BE6
color13 #CDB6F2
color6  #91D5EF
color14 #B6E5F6
color7  #C6D9E4
color15 #E7F2F7

cursor                  #91D5EF
cursor_text_color       #0B1621
url_color               #91D5EF
