# Antigone - Hyprland Colors
$border_active = rgba(8FD4FF66)
$border_inactive = rgba(5A738766)
$shadow = rgba(000000ee)
$bg = rgb(000000)
$fg = rgb(B0CCDC)
$accent = rgb(8FD4FF)
$orange = rgb(B62D66)
$orange_light = rgba(B62D6666)
