# Antigone - Kitty Terminal Colors (draft via theme-scaffold)
foreground              #B0CCDC
background              #000000
selection_foreground    #B0CCDC
selection_background    #5A7387

color0  #000000
color8  #5A7387
color1  #B62D66
color9  #B62D66
color2  #4BB5BE
color10 #BBF0EF
color3  #DEB45B
color11 #DEB45B
color4  #387AAA
color12 #8FD4FF
color5  #B62D66
color13 #B62D66
color6  #4BB5BE
color14 #BBF0EF
color7  #B0CCDC
color15 #BBF0EF

cursor                  #DEB45B
cursor_text_color       #000000
url_color               #8FD4FF
