# Serene - Hyprland Colors
$border_active = rgba(4A7F3F66)
$border_inactive = rgba(E8DFD066)
$shadow = rgba(FFF9F0ee)
$bg = rgb(FFF9F0)
$fg = rgb(3F4A43)
$accent = rgb(4A7F3F)
$orange = rgb(B85C45)
$orange_light = rgba(B85C4566)
