# Serene - Hyprland Colors
$border_active = rgba(3A633166)
$border_inactive = rgba(C8BEAB66)
$shadow = rgba(D6CFC3ee)
$bg = rgb(D6CFC3)
$fg = rgb(363F39)
$accent = rgb(3A6331)
$orange = rgb(8A4534)
$orange_light = rgba(8A453466)
