# Serene - cream / sage (from green-jade)
foreground              #363F39
background              #D6CFC3
selection_foreground    #363F39
selection_background    #C8BEAB

color0  #363F39
color8  #5B635C
color1  #8A4534
color9  #934F3D
color2  #3A6331
color10 #496D42
color3  #6E550E
color11 #7B5E12
color4  #35615A
color12 #406F68
color5  #725246
color13 #806053
color6  #31624E
color14 #3B705B
color7  #797266
color15 #888074

cursor                  #3A6331
cursor_text_color       #D6CFC3
url_color               #3A6331
