# Viridian - Kitty Terminal Colors
foreground              #E1ECE8
background              #10252A
selection_foreground    #10252A
selection_background    #9BBEB5

color0  #0B1B20
color8  #819C9F
color1  #CE9C9D
color9  #D4A8A9
color2  #9BBEB5
color10 #A5C4BC
color3  #C5BA98
color11 #CBC1A2
color4  #91AFBB
color12 #9CB7C2
color5  #B4ABC5
color13 #BCB3CB
color6  #A3C5C8
color14 #ACCBCE
color7  #E1ECE8
color15 #F0F6F3

cursor                  #F0F6F3
cursor_text_color       #10252A
url_color               #9BBEB5
