# Abyss - Kitty Terminal Colors
foreground              #A7C2CB
background              #05090C
selection_foreground    #DCEBEF
selection_background    #0E2A33

color0  #0D161B
color8  #34505C
color1  #D7786C
color9  #E69A8F
color2  #62C4A0
color10 #86D6B8
color3  #E3A558
color11 #F0C07E
color4  #4C92C6
color12 #74B0DC
color5  #9A8AD8
color13 #B7AAE6
color6  #4FC8CC
color14 #7FDCDF
color7  #A7C2CB
color15 #DCEBEF

cursor                  #4FC8CC
cursor_text_color       #05090C
url_color               #4FC8CC
