# Frost - Kitty Terminal Colors
foreground              #1D3342
background              #E3EDF1
selection_foreground    #10222E
selection_background    #BFDDE8

color0  #1D3342
color8  #4F6878
color1  #A8403A
color9  #B24A43
color2  #1F6E55
color10 #26785D
color3  #80570F
color11 #8A5E12
color4  #265C94
color12 #2D66A2
color5  #65479F
color13 #6E50AA
color6  #0F6F86
color14 #137890
color7  #5F7886
color15 #4A6270

cursor                  #13809A
cursor_text_color       #E3EDF1
url_color               #13809A
