# Cyber - Kitty Terminal Colors

foreground              #A0B4C5
background              #0A131C
selection_foreground    #A0B4C5
selection_background    #18324E

# Black
color0  #101B25
color8  #475772

# Red
color1  #905F59
color9  #BC8D73

# Green
color2  #5E8C9C
color10 #7BA6B5

# Yellow
color3  #D9C5A8
color11 #E6D7BE

# Blue
color4  #3D6390
color12 #6298D1

# Magenta
color5  #6E6A9C
color13 #8172A7

# Cyan
color6  #7297BB
color14 #9BB0D7

# White
color7  #A0B4C5
color15 #C8D6E0

# Cursor
cursor                  #7297BB
cursor_text_color       #0A131C

# URL underline color
url_color               #6298D1
