# Calliope - Hyprland Colors
$border_active = rgba(3E6FA866)
$border_inactive = rgba(1B243066)
$shadow = rgba(08090Bee)
$bg = rgb(08090B)
$fg = rgb(B4BAC2)
$accent = rgb(3E6FA8)
$orange = rgb(6A7078)
$orange_light = rgba(6A707866)
