# Ember - Kitty Terminal Colors (lofi-dusk palette)

foreground              #D0C3A8
background              #12161E
selection_foreground    #12161E
selection_background    #254A67

# Black
color0  #153551
color8  #4E5654

# Red
color1  #9D4A36
color9  #AE5D3B

# Green
color2  #5E8D90
color10 #6E93A3

# Yellow
color3  #B58F56
color11 #D69A73

# Blue
color4  #226590
color12 #486989

# Magenta
color5  #A07189
color13 #B96C7B

# Cyan
color6  #5E8D90
color14 #6E93A3

# White
color7  #D0C3A8
color15 #E6D7BE

# Cursor
cursor                  #D69A73
cursor_text_color       #12161E

# URL underline color
url_color               #B58F56
