# Silver - Kitty Terminal Colors
foreground              #D7DFE5
background              #202429
selection_foreground    #202429
selection_background    #D7DFE5

color0  #171B20
color8  #8795A2
color1  #D19A9D
color9  #D7A6A9
color2  #A7BEA9
color10 #B0C4B2
color3  #C7B995
color11 #CDC0A0
color4  #A7BBD0
color12 #B0C2D5
color5  #B8ABC7
color13 #BFB3CD
color6  #A8C1C7
color14 #B1C7CD
color7  #D7DFE5
color15 #F0F3F5

cursor                  #F0F3F5
cursor_text_color       #202429
url_color               #D7DFE5
