# Lagoon - Kitty Terminal Colors
foreground              #BAD8D6
background              #071A1D
selection_foreground    #E3F4F2
selection_background    #0F3A3E

color0  #0E2629
color8  #3B5E62
color1  #E3897D
color9  #F0A79C
color2  #8AD39A
color10 #A9E3B6
color3  #E2C07A
color11 #EFD59E
color4  #5DA6D1
color12 #85C1E6
color5  #AE9DDB
color13 #C6B8EA
color6  #5CD6C6
color14 #8AE4D6
color7  #BAD8D6
color15 #E3F4F2

cursor                  #5CD6C6
cursor_text_color       #071A1D
url_color               #5CD6C6
